// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibdzkidcpzbhhrltxuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZHpraWRjcHpiaGhybHR4dW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTg1MDQsImV4cCI6MjA3MTc3NDUwNH0.oYx4k17v7kOQDkmLcBtN0jBBt2SCvxHLWK14LiI7P8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});